module.exports = {
  apps: [
    {
      name: 'dev',
      script: 'node_modules/next/dist/bin/next',
      args: 'dev --webpack',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      description: 'Next.js dev server on port 3000',
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
      },
      error_file: './logs/dev-error.log',
      out_file: './logs/dev-out.log',
      log_file: './logs/dev-combined.log',
      time: true,
    },
    {
      name: 'prod',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      cwd: './',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      description: 'Next.js prod server on port 3000',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: './logs/prod-error.log',
      out_file: './logs/prod-out.log',
      log_file: './logs/prod-combined.log',
      time: true,
    },
  ],
};
